# Generated by Django 5.2.17 on 2026-09-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
