# Generated by Django 5.2.17 on 2026-09-04 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_test_datetime_test_time_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
